### ISSUE TITLE
etag mismatch returns a different error code by runtime

### ISSUE THREAD

**Issue by vinayada1** [dapr/php-sdk#19]
## Expected Behavior

dapr runtime changes the error code returned by the state apis for etag mismatch related errors and other errors. Check if the sdk needs a change. dapr/dapr#2647

## Actual Behavior

Check if sdk needs a change to distinguish between etag mismatch and other state api issues

## Steps to Reproduce the Problem

Error code internal is returned when state api fails due to etag mismatch error

## Release Note

RELEASE NOTE:

**Comment by withinboredom** [comment]
This doesn't appear to affect the php sdk
