### ISSUE TITLE
Use examples as e2e tests

### ISSUE THREAD

**Issue by withinboredom** [dapr/php-sdk#73]
## Describe the feature

Examples provide a fairly good surface for providing e2e tests. I wonder if we can use the examples directory to provide those tests.

## Release Note

RELEASE NOTE: **ADD** examples as e2e tests

**Comment by artursouza** [comment]
Not sure if this is already planned for this work, but @wcs1only has an auto-validation framework we use in our examples. It validates out of the commands from the README.md file. You can see the examples in any of our repos, including SDKs.

**Comment by withinboredom** [comment]
Oooh, yeah, I'll check that out! Thanks for the heads up?

**Comment by wcs1only** [comment]
> Oooh, yeah, I'll check that out! Thanks for the heads up!

https://github.com/dapr/mechanical-markdown/blob/main/examples/README.md the docs, which themselves are autovalidated :)

Don't hesitate to reach out if you have any questions.

**Comment by withinboredom** [comment]
This is done
