### ISSUE TITLE
Symfony integration

### ISSUE THREAD

**Issue by CvekCoding** [dapr/php-sdk#88]
## Symfony integration

Do you plan to describe how to integrate DAPR into Symfony properly?

**Comment by withinboredom** [comment]
If it supports DI natively (like Laravel) you should just be able to use it normally. There's [a Laravel example](https://github.com/dapr/php-sdk/blob/main/examples/laravel/app/Providers/DaprServiceProvider.php) that should be fairly similar.

**Comment by withinboredom** [comment]
Closing this and adding it to #6
